### ISSUE TITLE
TaxiEinstiegStatistik ruft Datenbank auf

### ISSUE THREAD

**Issue by Smadback** [Smadback/TaxiEinstiegStatistik#7]
Es wird beim Aufruf des Webservices die Datenbank aufgerufen und die Information von 12-13 Uhr als XML zurückgegeben

**Comment by MST01** [comment]
Provisorische Datenbank Abfrage mit Daten von 12 bis 13 Uhr; Übergeben
als XML an den Webservice dargestellt als Heatmap
